spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: api-config-server
  gateway:
    routes:
    - id: api-checkout-service
      uri: http://localhost:8081
      predicates:
      - Path=/checkout-service/**
server:
  port: 8084